### ISSUE TITLE
Chromakey node strange behavior in versions below 2021.2

### ISSUE THREAD

**Issue by spxyz** [keijiro/ShaderGraphAssets#1] opened 2021-11-09 20:02 UTC
Hi, thanks for your great assets.
I am having issues with chromakey node. Something strange with colors in unity version below 2021.2(HDRP setup):

![keyHDRP](https://user-images.githubusercontent.com/11527631/140995333-49b1c608-5b51-4b6d-808e-151baec82e56.jpg)

**Comment by keijiro** [comment] 2021-11-10 02:54
Does it reproduce on URP with Gamma color space setting?

I guess that this issue is caused by Linear color space setting.

**Comment by spxyz** [comment] 2021-11-10 06:11
That's what I thought, but:

[2021.2] Start new HDRP project (linear color space), import ShaderGraphAssets package - **OK**
[2021.2] Start new URP project (gamma color space), import ShaderGraphAssets package - **OK**

[2020.3] Start new HDRP project (linear color space), import ShaderGraphAssets package - **FAIL**
[2020.3] Start new URP project (gamma color space), import ShaderGraphAssets package - **FAIL**

**Comment by keijiro** [comment] 2021-11-10 06:26
Thanks for the clarification. Sure, I should deep-dive into it.

**Comment by keijiro** [comment] 2021-11-10 07:44
I found there is a compatibility-breaking change in the Swizzle node (it's actually upper compatible but not backward compatible). I think I can solve it by re-editing it in 2020.3.

**Comment by keijiro** [comment] 2021-11-10 08:47
Fixed in 1.0.5

**Comment by keijiro** [comment] 2021-11-10 08:48
I'm closing this issue now. Please feel free to reopen it if it still reproduces on your side.

**Closed as completed by keijiro** 2021-11-10 08:48 UTC
Labels: question

**Comment by spxyz** [comment] 2021-11-10 09:31
You're the Best!
